project: 
  type: website
  resources:
    - "google9541c230ce597c09. html"
    - "_site/cv/*"    # ADD THIS - or put cv files in a different location
    
website:
  google-analytics: G-4B73YXR349
  title: Seungju Kim
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: research/papers.qmd
      text: Research
    - href: resource.qmd
      text: Resources
    tools:
    - icon: github
      menu:
        - text: Source Code
          href:  https://github.com/follhim/follhim.github.io
        - text: Report a Bug
          href:  https://github.com/follhim/follhim.github.io/issues
  comments:
    giscus:
      repo: follhim/follhim.github.io
      theme: dark
format:
  html:
    toc: true
    theme: superhero
    html-meta:
      author: "Seungju Kim"
      description: "Seungju Kim's research website focusing on modeling the relationship between religiousness/spirituality and health, LGBTQ+ communities, and mental health. Clinical psychology researcher at University of Illinois Urbana-Champaign (UIUC)."
      keywords: "Seungju Kim, Kim Seungju, religion and health, LGBTQ research, mental health, spirituality research, psychology, clinical psychology, University of Illinois, Urbana, Champaign, UIUC"
      google-site-verification: "8o0g9lyitTlQOMMIfpCrywCM7SA5ldwWWewZTS16eiE"